export const LOAD_USER_TOKEN = 'LOAD_USER_TOKEN';
export const LOAD_USER_TOKEN_PAYLOAD = 'LOAD_USER_TOKEN_PAYLOAD';
export const ADD_STOCKS_DATA = 'ADD_STOCKS_DATA';
export const DELETE_STORE = 'DELETE_STORE';
